name: Commit And automerge PR
description: 'Commit And automerge PR'

inputs:
  github_token:
    description: 'Github token'
    required: true
  version:
    description: 'Version to commit'
    required: true
  repository:
    description: 'Repository name at github.com/standard-api'
    required: true
  path:
    description: 'path where is git root directory'
    required: false
    default: '.'

outputs:
  pr_number:
    description: "The number of the created pull request"
    value: ${{ steps.create.outputs.pr_number }}

runs:
  using: "composite"
  steps:
    - name: Set git user and email
      uses: ./.github/actions/set-git-username
    - name: Commit updated POM
      id: commit
      shell: bash
      run: |
        cd ${{ inputs.path }}
        git checkout -b dependency/${{ inputs.version }}
        git add pom.xml
        if git diff --quiet --exit-code; then
          echo "committed=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Increase version of standard-api/${{ inputs.repository }} dependency to ${{ inputs.version }}"
          git push https://${{ inputs.github_token }}@github.com/standard-api/${{ inputs.repository }}.git HEAD:dependency/${{ inputs.version }}
          echo "committed=true" >> $GITHUB_OUTPUT
        fi
    - name: Create Pull Request
      shell: bash
      if: ${{ steps.commit.outputs.committed == 'true' }}
      run: |
        cd ${{ inputs.path }}
        gh auth login --with-token <<< ${{ inputs.github_token }}
        PR_URL=$(gh pr create --repo standard-api/${{ inputs.repository }} \
          --title "Increase version of standard-api/${{ inputs.repository }} dependency to ${{ inputs.version }}" \
          --body "Auto PR for dependency upgrade of of standard-api/${{ inputs.repository }}" \
          --head dependency/${{ inputs.version }} \
          --base master)
        
        PR_NUMBER=$(echo $PR_URL | grep -o '[0-9]\+$')
        echo "::set-output name=pr_number::$PR_NUMBER"

    - name: Automatically merge PR
      shell: bash
      if: ${{ steps.commit.outputs.committed == 'true' }}
      run: |
        cd ${{ inputs.path }}
        gh pr merge ${{ steps.createReleasePR.outputs.pr_number }} \
        --subject "Increase version of standard-api/${{ inputs.repository }} dependency to ${{ inputs.version }}" \
        --squash \
        --admin \
        --delete-branch
      env:
        GH_TOKEN: ${{ inputs.github_token }}
    - name: Delete sandbox repository
      shell: bash
      run: |
        rm -rf ./sandbox