name: Commit npm version bump
description: 'Commit npm version bump'
inputs:
  version:
    description: 'Version to commit'
    required: true
  bump:
    description: 'Bump type (patch, minor or major)'
    required: true
  repository:
    description: 'Repository name at github.com/standard-api'
    required: true
runs:
  using: "composite"
  steps:
    - name: Commit updated version
      shell: bash
      run: |
        git add ${{ inputs.repository }}/system-graphql-schema/package.json
        git commit -m "Release new ${{ inputs.bump }} version ${{ inputs.version }} of npm packages" || true