name: Commit npm version bump
description: 'Commit npm version bump'
inputs:
  version:
    description: 'Version to commit'
    required: true
  bump:
    description: 'Bump type (patch, minor or major)'
    required: true
  package_path:
    description: 'Path to folder containing package.json'
    required: true
runs:
  using: "composite"
  steps:
    - name: Commit updated version
      shell: bash
      run: |
        git add ${{ inputs.package_path }}/package.json
        git commit -m "Release new ${{ inputs.bump }} version ${{ inputs.version }} of npm packages" || true