name: Commit And automerge PR
description: 'Commit And automerge PR'

inputs:
  github_token:
    description: 'Github token'
    required: true
  version:
    description: 'Version to commit'
    required: true
  repository:
    description: 'Repository name at github.com/standard-api'
    required: true

outputs:
  pr_number:
    description: "The number of the created pull request"
    value: ${{ steps.create.outputs.pr_number }}

runs:
  using: "composite"
  steps:
    - name: Commit updated POM
      shell: bash
      run: |
        git checkout -b dependency/${{ inputs.version }}
        git add **/pom.xml
        git add pom.xml
        git commit -m "Increase version of Stapi axon driver dependency to ${{ inputs.version }}"
        git push https://${{ inputs.github_token }}@github.com/standard-api/${{ inputs.repository }}.git HEAD:dependency/${{ inputs.version }}
    - name: Create Pull Request
      shell: bash
      run: |
        gh auth login --with-token <<< ${{ inputs.github_token }}
        PR_URL=$(gh pr create --repo standard-api/${{ inputs.repository }} \
          --title "Increase version of Stapi axon driver dependency to ${{ inputs.version }}" \
          --body "Auto PR for dependency upgrade of of Stapi axon driver" \
          --head dependency/${{ inputs.version }} \
          --base master)
        
        PR_NUMBER=$(echo $PR_URL | grep -o '[0-9]\+$')
        echo "::set-output name=pr_number::$PR_NUMBER"

    - name: Automatically merge PR
      shell: bash
      run: |
        gh pr merge ${{ steps.createReleasePR.outputs.pr_number }} \
        --subject "Increase version of Stapi axon driver dependency to ${{ inputs.version }}" \
        --squash \
        --admin \
        --delete-branch
      env:
        GH_TOKEN: ${{ inputs.github_token }}