name: Publish package to npm
description: 'Publish package to npm'
inputs:
  version:
    description: 'Version to publish'
    required: true
runs:
  using: "composite"
  steps:
    - name: Publish package
      shell: bash
      run: |
        cd system-graphql-schema
        npm publish
