name: Publish package to npm
description: 'Publish package to npm'
inputs:
  npm_token:
    description: 'Version to publish'
    required: true
runs:
  using: "composite"
  steps:
    - run: npm publish -access public
      shell: bash
      working-directory: ./system-graphql-schema
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
