name: Release new version

on:
  workflow_dispatch:
    inputs:
      semverBump:
        description: 'The type of Semantic Version bump (patch, minor or major)'
        required: true
        default: 'patch'
jobs:
  deploy-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      pull-requests: write
      contents: write
      repository-projects: write
    strategy:
      matrix:
        repo: ['standard-api/axon-driver']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven
        
      - name: Setup node with npm
        uses: ./.github/actions/setup-node-with-npm

      - name: Bump new Semantic Version in maven
        uses: ./.github/actions/bump-maven-version
        id: bumpedVersion
        with:
          bump: ${{ github.event.inputs.semverBump }}

      - name: Set version in npm
        uses: ./.github/actions/set-npm-version
        with:
          version: ${{ steps.bumpedVersion.outputs.version }}
          package_path: system-graphql-schema

      - name: Set git user and email
        uses: ./.github/actions/set-git-username

      - name: Create release commit for maven
        uses: ./.github/actions/create-release-commit-maven
        with:
          bump: ${{ github.event.inputs.semverBump }}
          version: ${{ steps.bumpedVersion.outputs.version }}

      - name: Create release commit for npm
        uses: ./.github/actions/create-release-commit-npm
        with:
          bump: ${{ github.event.inputs.semverBump }}
          version: ${{ steps.bumpedVersion.outputs.version }}
          package_path: system-graphql-schema

      - name: Create release PR and automatic merge
        if: ${{ steps.bumpedVersion.outputs.was_bumped == 'true' }}
        uses: ./.github/actions/create-release-pr-and-merge
        with:
          github_token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          bump: ${{ github.event.inputs.semverBump }}
          version: ${{ steps.bumpedVersion.outputs.version }}
          repository: axon-driver

      - name: Checkout updated master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Check if version exists on Sonatype
        uses: ./.github/actions/check-sonatype-version
        id: check_version_sonatype
        with:
          group_id: 'ai.stapi'
          artifact_id: 'axon-driver'
          version: ${{ steps.bumpedVersion.outputs.version }}

      - name: Check if version exists on NPM
        uses: ./.github/actions/check-npm-version
        id: check_version_npm
        with:
          package_name: '@standard-api/system-graphql-schema'
          version: ${{ steps.bumpedVersion.outputs.version }}

      - name: Setup JDK for sonatype release
        uses: ./.github/actions/setup-jdk-for-sonatype-release
        with:
          ossrh_gpg_secret_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

      - name: Deploy release to Sonatype
        if: ${{ steps.check_version_sonatype.outputs.version_exists == 'false' }}
        uses: ./.github/actions/deploy-sonatype-all-in-order
        with:
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_token: ${{ secrets.OSSRH_TOKEN }}
          ossrh_gpg_secret_key_password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Deploy release to NPM
        if: ${{ steps.check_version_npm.outputs.version_exists == 'false' }}
        uses: ./.github/actions/deploy-npm
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - name: Tag the release idempotently
        run: |
          if ! git ls-remote --tags origin | grep ${{ steps.bumpedVersion.outputs.version }} >/dev/null; then
            git tag ${{ steps.bumpedVersion.outputs.version }}
            git push origin ${{ steps.bumpedVersion.outputs.version }}
          fi

      - name: Check if release exists
        id: check_release
        uses: ./.github/actions/check-github-release-exists
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.bumpedVersion.outputs.version }}

      - name: Publish release on github
        id: publish_release_github
        if: steps.check_release.outputs.exists == 'false'
        uses: ./.github/actions/publish-release-github
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_version: ${{ steps.bumpedVersion.outputs.version }}

      - name: Publish release notifications
        if: steps.check_release.outputs.exists == 'false'
        uses: ./.github/actions/publish-release-notifications
        with:
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          release_version: ${{ steps.bumpedVersion.outputs.version }}
          repository: "standard-api/axon-driver"
          changelog: ${{ steps.publish_release_github.outputs.changelog }}

      - name: Checkout stapi sandbox repository code
        uses: actions/checkout@v3
        with:
          repository: standard-api/sandbox
          path: ./sandbox
          token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
      
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Upgrade version of Stapi Axon Driver in Sandbox app
        run: |
          cd ./sandbox
          old_version=$(xmllint --xpath "//*[local-name()='properties']/*[local-name()='stapi.axon.version']/text()" pom.xml)
          echo "Old version is $old_version"
          new_version=${{ steps.bumpedVersion.outputs.version }}
          echo "New version is ${{ steps.bumpedVersion.outputs.version }}"
          sed -i "s|<stapi.axon.version>$old_version</stapi.axon.version>|<stapi.axon.version>$new_version</stapi.axon.version>|g" pom.xml

      - name: Create commit, PR and automatic merge of pom upgrade in Sandbox
        uses: ./.github/actions/commit-pr-merge-update-pom-version
        with:
          github_token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          version: ${{ steps.bumpedVersion.outputs.version }}
          repository: sandbox
          path: ./sandbox

      - name: Checkout updated master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set next SNAPSHOT version
        uses: ./.github/actions/bump-maven-version
        id: bumpedVersionSnapshot
        with:
          bump: 'snapshot'

      - name: Create snapshot commit using PR and automatic merge
        uses: ./.github/actions/create-snapshot-commit
        with:
          github_token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          version: ${{ steps.bumpedVersionSnapshot.outputs.version }}
          repository: axon-driver
          bump: 'snapshot'
          
      - name: Dispatch Event about succesfull release
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: axon-driver-released
          client-payload: '{"version": "${{ steps.bumpedVersion.outputs.version }}","snapshot_version": "${{ steps.bumpedVersionSnapshot.outputs.version }}"}'
