name: Upgrade version of Stapi Core

on:
  repository_dispatch:
    types: [stapi-core-released]

jobs:
  upgrade-stapi-core:
    runs-on: ubuntu-latest
    environment: myenvironment
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Wait for new version of Core library on Sonatype
        run: |
          while : 
          do
          echo "Checking for version ${{ github.event.client_payload.new_version }} on Sonatype..."
          if curl -s "https://repo1.maven.org/maven2/ai/stapi/core/maven-metadata.xml" | xmllint --xpath "//*[local-name()='versions']/*[local-name()='version']/text()" - | grep -q "${{ github.event.client_payload.new_version }}"; then
          echo "Version ${{ github.event.client_payload.new_version }} found!"
          break
          fi
          echo "Version not found on sonatype yet, waiting for 1 minute..."
          sleep 60
          done

      - name: Upgrade version of Stapi Core
        run: |
          old_version=$(xmllint --xpath "//*[local-name()='properties']/*[local-name()='stapi.core.version']/text()" pom.xml)
          new_version=${{ github.event.client_payload.new_version }}
          sed -i "s|<stapi.core.version>$old_version</stapi.core.version>|<stapi.core.version>$new_version</stapi.core.version>|g" pom.xml

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven

      - name: Build and check
        uses: ./.github/actions/build-and-check
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Create commit, PR and automatic merge of pom upgrade in axon-driver repository
        uses: ./.github/actions/commit-pr-merge-update-pom-version
        with:
          github_token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          version: ${{ github.event.client_payload.new_version }}
          repository: core
          
      - name: Trigger new release of new patch or minor version
        if: ${{ github.event.client_payload.bumpType != 'major' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: axon-driver-updated
          client-payload: '{"new_version": "${{ steps.bumpedVersion.outputs.version }}","new_snapshot_version": "${{ steps.bumpedVersionSnapshot.outputs.version }}","bumpType": "${{ github.event.inputs.semverBump }}"}'
